In [2]:
#Create a function named calculate() in mean_var_std.py that 
#uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, 
#columns, and elements in a 3 x 3 matrix.
#The input of the function should be a list containing 9 digits. 
#The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, 
#variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

In [6]:
import numpy as np

In [ ]:
#step 1: Converting the list into 3 X 3 matrix

In [7]:
list =[0,1,2,3,4,5,6,7,8]
num_array= np.array(list).reshape([3,3])
print(num_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#calculating mean

In [13]:
mean_row = num_array.mean(axis = 0).tolist()
mean_col = num_array.mean(axis = 1).tolist()
mean_val = num_array.mean()


In [14]:
#calculating variance

In [16]:
var_row =num_array.var(axis=0).tolist()
var_col =num_array.var(axis=1).tolist()
var_val=num_array.var()


In [ ]:
#calculating standard deviation

In [17]:
std_row =num_array.std(axis=0).tolist()
std_col=num_array.std(axis=1).tolist
std_val =num_array.std()

In [18]:
#calcluating max, min and sum across rows, columns and matrix

In [19]:
max_row =num_array.max(axis=0).tolist()
max_col=num_array.max(axis=1).tolist
max_val =num_array.max()

min_row =num_array.min(axis=0).tolist()
min_col=num_array.min(axis=1).tolist
min_val =num_array.min()

sum_row =num_array.sum(axis=0).tolist()
sum_col=num_array.sum(axis=1).tolist
sum_val =num_array.sum()

In [21]:
#Converting the results into a dictionary and then printing it

In [24]:
calculations ={}
calculations = {'mean':[mean_row, mean_col, mean_val],
               'variance' :[var_row, var_col, var_val],
                'standard deviation' : [std_row, std_col, std_val],
                'min': [min_row, min_col, min_val],
                'max':[max_row, max_col, max_val],
                'sum': [sum_row,sum_col,sum_val]
               }

In [25]:
print(calculations)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], <built-in method tolist of numpy.ndarray object at 0x00000177D334C570>, 2.581988897471611], 'min': [[0, 1, 2], <built-in method tolist of numpy.ndarray object at 0x00000177D0968570>, 0], 'max': [[6, 7, 8], <built-in method tolist of numpy.ndarray object at 0x00000177D31CDC30>, 8], 'sum': [[9, 12, 15], <built-in method tolist of numpy.ndarray object at 0x00000177D334C6F0>, 36]}
